### ISSUE TITLE
Make issue list interactive

### ISSUE THREAD

**Issue by mattii** [noxan/gi-cli#18]
Would be great to select an issue of the loaded list by navigating with arrow keys and hitting enter. Inquirer will be helpful, here: https://www.npmjs.com/package/inquirer

**Comment by noxan** [comment]
Cool idea! 😎 

Would love to see this with a feature flag or as configuration option.

**Comment by mattii** [comment]
Yes! Maybe `gi list -i` and in the configuration file a new boolean field `interactive_list`? If the configuration is set to `true`, the list will always be interactive.

**Comment by mattii** [comment]
Closed with https://github.com/noxan/gi-cli/pull/21.
